"""
Stage 2: Grounding Checker — Context-Aware (v3)
Deterministic, no LLM, no embeddings, no external services.

Aliases for field names are generated by the LLM once per extraction
(via generate_field_aliases()) and injected into GroundingChecker.check().
The grounding logic itself remains fully deterministic.

Grounding priority (strongest evidence wins):
  1. Key-Value Pair Match          → grounded / ungrounded
  2. Numeric Context Match         → grounded / ungrounded  (numeric fields only)
  3. Window-Based Context Match    → grounded
  4. Exact Document Match          → partial  (value present, context absent)
  5. Token Overlap Match           → partial  (weak fallback)
  → ungrounded if nothing passes

Public API:
    # Generate aliases once (call from extraction engine)
    aliases = generate_field_aliases(field_names, groq_provider, model)

    # Pass aliases into checker
    checker.check(data, document_text, schema_dict, field_aliases=aliases)
"""
import json
import re
import logging
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Status constants
# ---------------------------------------------------------------------------
GROUNDED = "grounded"
PARTIAL = "partial"
UNGROUNDED = "ungrounded"
SKIPPED = "skipped"

# ---------------------------------------------------------------------------
# Tuning
# ---------------------------------------------------------------------------
_WINDOW_CHARS = 150       # ± chars around alias occurrence (expanded to avoid left-context clipping)
_TOKEN_PARTIAL = 0.50     # token overlap threshold for PARTIAL

_ALIAS_PROMPT = """Given these schema field names, return a JSON object mapping each field name to a list of 3-6 short synonyms or alternative terms that would appear in a document to label that field.

Field names: {field_names}

Rules:
- Synonyms must be common document label words (e.g. "invoice number" -> ["inv", "bill no", "invoice #"])
- Keep each synonym short (1-4 words)
- No duplicates of the field name itself
- Return ONLY valid JSON, no extra text

Example output:
{{"invoice_number": ["inv", "bill no", "invoice #"], "total_amount": ["total", "amount due", "sum"]}}"""


def generate_field_aliases(
    field_names: List[str],
    groq_provider,
    model: str = "llama-3.3-70b-versatile",
) -> Dict[str, List[str]]:
    """
    Ask the LLM to generate document synonyms for each field name.
    Called once per extraction before grounding.
    Returns {field_name: [alias1, alias2, ...]}
    Falls back to empty dict on any error (grounding still works via field tokens).
    """
    if not field_names:
        return {}
    try:
        prompt = _ALIAS_PROMPT.format(field_names=", ".join(field_names))
        result = groq_provider.generate_json(
            prompt=prompt,
            model=model,
            temperature=0.0,
            max_tokens=512,
        )
        # Validate: keep only lists of strings
        aliases = {}
        for field, syns in result.items():
            if isinstance(syns, list):
                aliases[field] = [s for s in syns if isinstance(s, str) and s.strip()]
        logger.debug(f"LLM aliases generated for {len(aliases)} fields")
        return aliases
    except Exception as e:
        logger.warning(f"Alias generation failed, falling back to field tokens: {e}")
        return {}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _normalize(text: str) -> str:
    """Lowercase, strip structural whitespace noise (newlines, tabs, excess spaces)."""
    text = text.lower()
    text = re.sub(r"[\n\t\r]+", " ", text)   # collapse newlines/tabs to space
    text = re.sub(r" {2,}", " ", text)        # collapse repeated spaces
    return text.strip()


# LaTeX command → plain-text replacements applied before any matching
_LATEX_REPLACEMENTS = [
    (re.compile(r"\\Omega\b"), "Ω"),
    (re.compile(r"\\omega\b"), "ω"),
    (re.compile(r"\\mu\b"),    "μ"),
    (re.compile(r"\\pi\b"),    "π"),
    (re.compile(r"\\alpha\b"), "α"),
    (re.compile(r"\\beta\b"),  "β"),
    (re.compile(r"\\Delta\b"), "Δ"),
    (re.compile(r"\\delta\b"), "δ"),
    (re.compile(r"\\approx\b"), "≈"),
    (re.compile(r"\\times\b"), "×"),
    (re.compile(r"\\cdot\b"),  "·"),
    (re.compile(r"\\[a-zA-Z]+"), " "),   # any remaining \command → space
]
_LATEX_MATH_CHARS = re.compile(r"[\$\{\}\^\_\=]")


def _strip_latex(text: str) -> str:
    """
    Remove LaTeX formatting noise before string matching.
    - Maps known Greek/engineering symbols to unicode equivalents.
    - Strips remaining \\command words.
    - Removes math-block wrapper characters: $ { } ^ _ =
    """
    for pattern, replacement in _LATEX_REPLACEMENTS:
        text = pattern.sub(replacement, text)
    text = _LATEX_MATH_CHARS.sub(" ", text)
    text = re.sub(r" {2,}", " ", text)  # collapse any double-spaces introduced
    return text


def _tokenize(text: str) -> List[str]:
    """Lowercase alphanum tokens of length > 1."""
    return [t for t in re.split(r"\W+", text.lower()) if len(t) > 1]


def _field_tokens(field_name: str) -> set:
    """'employee_count' → {'employee', 'count'}"""
    return set(t for t in re.split(r"[_\s]+", field_name.lower()) if len(t) > 1)


def _get_aliases(field_name: str, field_aliases: Dict[str, List[str]]) -> List[str]:
    """
    Build the search-term list for a field.
    Uses LLM-generated aliases (injected) + the field's own tokens as fallback.
    """
    # Start with the field's own tokens (always included as baseline)
    seen: set = set()
    aliases: List[str] = []
    for t in _field_tokens(field_name):
        if t not in seen:
            seen.add(t)
            aliases.append(t)

    # Add LLM-generated aliases for this specific field
    for a in field_aliases.get(field_name, []):
        if a not in seen:
            seen.add(a)
            aliases.append(a)

    return aliases


def _extract_kv_map(document_text: str) -> Dict[str, str]:
    """
    Lightweight regex-based key-value extractor.
    Captures "Key: value" / "Key - value" / "Key = value" patterns.
    Returns {normalized_key: normalized_value}
    """
    kv: Dict[str, str] = {}
    pattern = re.compile(
        r"([A-Za-z][A-Za-z0-9 _/]{1,40}?)"  # key
        r"\s*[:=\-]\s*"                       # separator
        r"([^\n\r,;]{1,100})",                # value (same line)
        re.MULTILINE,
    )
    for m in pattern.finditer(document_text):
        key = _normalize(m.group(1))
        val = _normalize(m.group(2))
        if key and val:
            kv[key] = val
    return kv


def _normalize_field_for_kv(field_name: str) -> str:
    return field_name.lower().replace("_", " ").strip()


def _find_windows(
    document_text: str,
    aliases: List[str],
    window: int = _WINDOW_CHARS,
) -> List[Tuple[str, str]]:
    """
    For each alias occurrence return (alias, context_snippet).
    Window is ± chars around the alias.
    """
    doc_lower = document_text.lower()
    results: List[Tuple[str, str]] = []
    for alias in aliases:
        start = 0
        while True:
            idx = doc_lower.find(alias.lower(), start)
            if idx == -1:
                break
            lo = max(0, idx - window)
            hi = min(len(document_text), idx + len(alias) + window)
            snippet = document_text[lo:hi]
            results.append((alias, snippet.lower()))
            start = idx + 1
    return results


def _nearest_number(alias: str, document_text: str) -> Optional[str]:
    """
    Fix #3: Find the nearest numeric token to an alias occurrence.
    Returns the closest number as a string, or None if not found.
    Strategy: scan right from alias position first, then left.
    """
    doc_lower = document_text.lower()
    number_re = re.compile(r"[\$£€]?\s*(\d[\d,\.]*\s*[a-zA-Z%Ω]*)")

    idx = doc_lower.find(alias.lower())
    if idx == -1:
        return None

    # Search in a tight window to the right first (most common KV pattern)
    right_slice = document_text[idx: idx + _WINDOW_CHARS]
    right_match = number_re.search(right_slice)

    left_slice = document_text[max(0, idx - _WINDOW_CHARS): idx]
    left_match = None
    for m in number_re.finditer(left_slice):
        left_match = m  # keep last (closest to alias)

    if right_match and left_match:
        # Pick whichever is closer to the alias position
        right_dist = right_match.start()
        left_dist = len(left_slice) - left_match.end()
        raw = right_match.group(1) if right_dist <= left_dist else left_match.group(1)
    elif right_match:
        raw = right_match.group(1)
    elif left_match:
        raw = left_match.group(1)
    else:
        return None

    return raw.replace(",", "").strip()


def _numeric_str(value: Any) -> str:
    """Normalise a numeric value to a plain string for comparison."""
    if isinstance(value, float) and value == int(value):
        return str(int(value))
    return str(value).replace(",", "").strip()


# ---------------------------------------------------------------------------
# Strategy functions
# Return GROUNDED | PARTIAL | UNGROUNDED | None
# None = strategy not applicable or inconclusive → try next
# ---------------------------------------------------------------------------

def _strategy_kv(
    field_name: str,
    value: Any,
    kv_map: Dict[str, str],
    field_aliases: Dict[str, List[str]],
) -> Tuple[Optional[str], Optional[str]]:
    """
    Strategy 1: Key-Value Pair Match.
    Returns (status, evidence_snippet).
    Key match + value match   → GROUNDED
    Key match + value differs → UNGROUNDED  (strong negative, stop here)
    No key match              → None
    """
    aliases = _get_aliases(field_name, field_aliases)
    field_key = _normalize_field_for_kv(field_name)
    candidate_keys = [field_key] + [_normalize(a) for a in aliases]

    extracted_norm = _normalize(str(value)).replace("$", "").replace(",", "").strip()

    for ck in candidate_keys:
        for kv_key, kv_val in kv_map.items():
            if ck in kv_key or kv_key in ck:
                kv_val_norm = kv_val.replace("$", "").replace(",", "").strip()
                evidence = f"{kv_key}: {kv_val}"
                if extracted_norm in kv_val_norm or kv_val_norm in extracted_norm:
                    return GROUNDED, evidence
                return UNGROUNDED, evidence  # key found, wrong value

    return None, None


def _strategy_numeric_context(
    field_name: str,
    value: Any,
    document_text: str,
    field_aliases: Dict[str, List[str]],
) -> Tuple[Optional[str], Optional[str]]:
    """
    Strategy 2: Alias → Nearest Number binding.
    Only for int/float.
    Finds each alias occurrence and compares the nearest numeric token.
    """
    if not isinstance(value, (int, float)):
        return None, None

    aliases = _get_aliases(field_name, field_aliases)
    expected = _numeric_str(value)

    for alias in aliases:
        nearest = _nearest_number(alias, document_text)
        if nearest is None:
            continue
        evidence = f"near '{alias}': {nearest}"
        if nearest == expected:
            return GROUNDED, evidence
        else:
            return UNGROUNDED, evidence

    return None, None


def _strategy_window_context(
    field_name: str,
    value: Any,
    document_text: str,
    field_aliases: Dict[str, List[str]],
) -> Tuple[Optional[str], Optional[str]]:
    """
    Strategy 3: Window-Based Context Match.
    Value must appear verbatim inside a ±80-char window around an alias.
    """
    aliases = _get_aliases(field_name, field_aliases)
    windows = _find_windows(document_text, aliases, _WINDOW_CHARS)

    if not windows:
        return None, None

    v = _normalize(str(value))
    for alias, snippet in windows:
        if v in snippet:
            return GROUNDED, f"near '{alias}': ...{snippet.strip()[:60]}..."

    return None, None


def _strategy_exact(
    value: Any,
    doc_lower: str,
) -> Tuple[Optional[str], Optional[str]]:
    """
    Strategy 4: Exact document match — demoted to PARTIAL (fix #5).
    The value exists in the document but no field context was found.
    Skipped for numerics (they must pass context strategies).
    """
    if isinstance(value, (int, float)):
        return None, None  # numerics require context

    v = _normalize(str(value))
    if not v or v in ("none", "null", "n/a"):
        return GROUNDED, "null/none value"

    if v in doc_lower:
        # Value found but no contextual evidence → PARTIAL, not GROUNDED
        return PARTIAL, f"value '{v}' found in document (no field context)"

    return None, None


def _strategy_token_overlap(
    value: Any,
    doc_lower: str,
) -> Tuple[str, Optional[str]]:
    """
    Strategy 5: Token overlap fallback. Always returns a definitive status.
    Best result is PARTIAL — token overlap alone never grants GROUNDED.
    """
    if isinstance(value, bool):
        return GROUNDED, "boolean — inferred value"

    v = _normalize(str(value))
    if not v or v in ("none", "null", "n/a", "true", "false"):
        return GROUNDED, "null/boolean value"

    tokens = _tokenize(v)
    if not tokens:
        return GROUNDED, "no checkable tokens"

    hits = sum(1 for t in tokens if t in doc_lower)
    ratio = hits / len(tokens)

    evidence = f"token overlap {hits}/{len(tokens)} = {ratio:.0%}"
    if ratio >= _TOKEN_PARTIAL:
        return PARTIAL, evidence
    return UNGROUNDED, evidence


# ---------------------------------------------------------------------------
# Per-field dispatcher
# ---------------------------------------------------------------------------

def _check_field_value(
    field_name: str,
    value: Any,
    document_text: str,
    doc_lower: str,
    kv_map: Dict[str, str],
    field_aliases: Dict[str, List[str]],
) -> Tuple[str, Optional[str]]:
    """
    Run strategies in priority order.
    Returns (status, evidence_snippet).
    """
    if value is None or value == "" or value == [] or value == {}:
        return SKIPPED, None

    if isinstance(value, bool):
        return GROUNDED, "boolean — inferred value"

    # --- Lists ---
    if isinstance(value, list):
        if not value:
            return SKIPPED, None
        item_results = [
            _check_field_value(field_name, item, document_text, doc_lower, kv_map, field_aliases)
            for item in value
        ]
        statuses = [r[0] for r in item_results]
        grounded_count = statuses.count(GROUNDED)
        partial_count = statuses.count(PARTIAL)
        total = len(statuses)
        match_ratio = round((grounded_count + 0.5 * partial_count) / total, 2)
        evidence = (
            f"list: {grounded_count}/{total} grounded, "
            f"{partial_count}/{total} partial, ratio={match_ratio}"
        )
        if grounded_count == total:
            return GROUNDED, evidence
        if grounded_count + partial_count == 0:
            return UNGROUNDED, evidence
        return PARTIAL, evidence

    # --- Dicts ---
    if isinstance(value, dict):
        leaves = [(k, v) for k, v in value.items() if v is not None]
        if not leaves:
            return SKIPPED, None
        sub_results = [
            _check_field_value(f"{field_name}.{k}", v, document_text, doc_lower, kv_map, field_aliases)
            for k, v in leaves
        ]
        statuses = [r[0] for r in sub_results]
        if all(s == GROUNDED for s in statuses):
            return GROUNDED, "all dict values grounded"
        if all(s == UNGROUNDED for s in statuses):
            return UNGROUNDED, "no dict values grounded"
        return PARTIAL, f"dict: {statuses.count(GROUNDED)}/{len(statuses)} grounded"

    # --- Scalars: strategy chain ---
    status, evidence = _strategy_kv(field_name, value, kv_map, field_aliases)
    if status is not None:
        logger.debug(f"  [{field_name}={value!r}] KV → {status} | {evidence}")
        return status, evidence

    status, evidence = _strategy_numeric_context(field_name, value, document_text, field_aliases)
    if status is not None:
        logger.debug(f"  [{field_name}={value!r}] NumericCtx → {status} | {evidence}")
        return status, evidence

    status, evidence = _strategy_window_context(field_name, value, document_text, field_aliases)
    if status is not None:
        logger.debug(f"  [{field_name}={value!r}] WindowCtx → {status} | {evidence}")
        return status, evidence

    status, evidence = _strategy_exact(value, doc_lower)
    if status is not None:
        logger.debug(f"  [{field_name}={value!r}] Exact → {status} | {evidence}")
        return status, evidence

    status, evidence = _strategy_token_overlap(value, doc_lower)
    logger.debug(f"  [{field_name}={value!r}] TokenOverlap → {status} | {evidence}")
    return status, evidence


# ---------------------------------------------------------------------------
# Public class
# ---------------------------------------------------------------------------

class GroundingChecker:
    """
    Context-aware deterministic grounding checker (v3).

    Public API unchanged:
        checker.check(data, document_text, schema_dict)
        → (per_field_grounding: Dict[str, str], grounding_score: float)

    Additional attribute after check():
        checker.evidence  →  Dict[str, str]  per-field explanation snippets
    """

    def __init__(self):
        self.evidence: Dict[str, Optional[str]] = {}

    def check(
        self,
        data: Dict[str, Any],
        document_text: str,
        schema_dict: Dict[str, Any],
        field_aliases: Optional[Dict[str, List[str]]] = None,
    ) -> Tuple[Dict[str, str], float]:
        """
        Args:
            data: Extracted data dict
            document_text: Raw source document text
            schema_dict: Schema with 'fields' key
            field_aliases: LLM-generated aliases per field name.
                           Generate with generate_field_aliases() before calling.
                           Falls back to field tokens only if None.

        Returns:
            (per_field_grounding, grounding_score)

        Side effect:
            self.evidence is populated with per-field snippets for explainability.
        """
        fields = schema_dict.get("fields", {})
        # Normalise LaTeX formatting before any matching
        document_text = _strip_latex(document_text)
        doc_lower = document_text.lower()
        kv_map = _extract_kv_map(document_text)
        aliases = field_aliases or {}
        logger.debug(f"KV map: {len(kv_map)} entries, aliases provided for {len(aliases)} fields")

        results: Dict[str, str] = {}
        self.evidence = {}
        checkable = 0
        weighted_score = 0.0

        for field_name in fields:
            value = data.get(field_name)
            status, ev = _check_field_value(
                field_name, value, document_text, doc_lower, kv_map, aliases
            )
            results[field_name] = status
            self.evidence[field_name] = ev

            logger.debug(f"Grounding [{field_name}={value!r}] → {status} | {ev}")

            if status != SKIPPED:
                checkable += 1
                if status == GROUNDED:
                    weighted_score += 1.0
                elif status == PARTIAL:
                    weighted_score += 0.5

        score = round(weighted_score / checkable, 3) if checkable else 1.0
        logger.debug(f"Grounding score: {score}")
        return results, score
